### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by kevin25** [dmelo/you2better#1]
Hello, i got these errors:

[Thu Sep 10 03:43:10.306154 2015] [:error] [pid 3939] [client 192.168.91.1:65167] PHP Warning:  include_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/test/index.php on line 9
[Thu Sep 10 03:43:10.306323 2015] [:error] [pid 3939] [client 192.168.91.1:65167] PHP Warning:  include_once(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear:/var/www/html/test/../../../:/var/www/html/test/../../:/var/www/html/test/../:/var/www/html/test:/var/www/html/test/../../../application/configs/') in /var/www/html/test/index.php on line 9
[Thu Sep 10 03:43:10.306868 2015] [:error] [pid 3939] [client 192.168.91.1:65167] PHP Warning:  include(you2better-conf.php): failed to open stream: No such file or directory in /var/www/html/test/index.php on line 19
[Thu Sep 10 03:43:10.307048 2015] [:error] [pid 3939] [client 192.168.91.1:65167] PHP Warning:  include(): Failed opening 'you2better-conf.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear:/var/www/html/test/../../../:/var/www/html/test/../../:/var/www/html/test/../:/var/www/html/test:/var/www/html/test/../../../application/configs/') in /var/www/html/test/index.php on line 19
[Thu Sep 10 03:43:10.307102 2015] [:error] [pid 3939] [client 192.168.91.1:65167] PHP Fatal error:  Class 'Monolog\Logger' not found in /var/www/html/test/index.php on line 20
[Thu Sep 10 03:43:13.930913 2015] [:error] [pid 8467] [client 192.168.91.1:65168] PHP Warning:  include_once(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/test/index.php on line 9
[Thu Sep 10 03:43:13.931081 2015] [:error] [pid 8467] [client 192.168.91.1:65168] PHP Warning:  include_once(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear:/var/www/html/test/../../../:/var/www/html/test/../../:/var/www/html/test/../:/var/www/html/test:/var/www/html/test/../../../application/configs/') in /var/www/html/test/index.php on line 9
[Thu Sep 10 03:43:13.931479 2015] [:error] [pid 8467] [client 192.168.91.1:65168] PHP Warning:  include(you2better-conf.php): failed to open stream: No such file or directory in /var/www/html/test/index.php on line 19
[Thu Sep 10 03:43:13.931559 2015] [:error] [pid 8467] [client 192.168.91.1:65168] PHP Warning:  include(): Failed opening 'you2better-conf.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear:/var/www/html/test/../../../:/var/www/html/test/../../:/var/www/html/test/../:/var/www/html/test:/var/www/html/test/../../../application/configs/') in /var/www/html/test/index.php on line 19
[Thu Sep 10 03:43:13.931614 2015] [:error] [pid 8467] [client 192.168.91.1:65168] PHP Fatal error:  Class 'Monolog\Logger' not found in /var/www/html/test/index.php on line 20

can you tell me what's wrong and how i can install it? Thanks!

**Comment by dmelo** [comment]
Hi. I'm truly sorry about the delay. I have changed a few thing and added install instructions on the README.
